# Generated by Django 5.1.7 on 2025-03-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_jobdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
