# Generated by Django 5.1.7 on 2025-03-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_resume_name_resume_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
