# Generated by Django 5.1.7 on 2025-05-10 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['category', 'subcategory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=1.0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume_screening.resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='resume_screening.skill')),
            ],
            options={
                'unique_together': {('resume', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.FloatField(default=1.0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume_screening.jobdescription')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='resume_screening.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
