# Generated by Django 4.2.3 on 2025-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0002_skill_resumeskill_jobskill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumeskill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='context_importance',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='matched_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='mention_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='position_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skill_level',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeskill',
            name='base_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='resumeskill',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeskill',
            name='context_importance',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='resumeskill',
            name='matched_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumeskill',
            name='skill_level',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='unspecified', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'subcategory'], name='resume_scre_categor_89e9d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='resumeskill',
            constraint=models.UniqueConstraint(fields=('resume', 'skill'), name='unique_resume_skill'),
        ),
    ]
