# Generated by Django 5.1.7 on 2025-03-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProcessedJobDesc',
        ),
    ]
